FORMAT: 1A

# SSS Application
API Mockup for SSS application

# Group Categories
API for **Category**

## Categories Collection [/categories]
### List all Categories [GET]
+ Response 200 (application/json)

    + Header
    
            X-Application: ZGVtb2RlbW9kZW1v
            
    + Body
    
            {
            "code": 0,
            "data": [
                    {
                      "id": 1, "name": "Nokia"
                    }, 
                    {
                      "id": 2, "name": "Apple"
                    }
                ]
            }

## Category [/category/{id}]
Get detail of a category

+ Parameters
    + id (required, number, `1`) ... Id of a category

### Retrieve detail of a Category [GET]
+ Response 200 (application/json)

    + Header

            X-Application: ZGVtb2RlbW9kZW1v

    + Body
    
            {
                "code": 0,
                "data": { 
                    "id": 1, 
                    "name": "Nokia"
                }
            }
            
# Group Products
API for **Product**

## Products Collection [/products]
### List all Products [GET]
+ Response 200 (application/json)

    + Header
    
            X-Application: ZGVtb2RlbW9kZW1v
            
    + Body
    
            {
                "code": 0,
                "data": [
                    {
                      "id": 1, "name": "Lumia 520", "price": 250, "thumb": "http:\/\/placekitten.com\/200\/300"
                    }, 
                    {
                      "id": 2, "name": "Lumia 620", "price": 300, "thumb": "http:\/\/placekitten.com\/250\/300"
                    },
                    {
                      "id": 3, "name": "Lumia 720", "price": 350, "thumb": "http:\/\/placekitten.com\/300\/300"
                    },
                    {
                      "id": 4, "name": "Lumia 820", "price": 400, "thumb": "http:\/\/placekitten.com\/350\/300"
                    },
                    {
                      "id": 5, "name": "Lumia 920", "price": 450, "thumb": "http:\/\/placekitten.com\/400\/300"
                    }
                ]
            }

## Product [/product/{id}]
Get detail of a product

+ Parameters
    + id (required, number, `1`) ... Id of a product

### Retrieve detail of a Product [GET]
+ Response 200 (application/json)

    + Header

            X-Application: ZGVtb2RlbW9kZW1v

    + Body
            
            {
                "code": 0,
                "data": {
                    "id": 3, 
                    "name": "Lumia 720", 
                    "price": 350,
                    "thumb": "http:\/\/placekitten.com\/300\/300",
                    "orignal": "http:\/\/placekitten.com\/700\/700"
                }
            }
            
# Group Users
API for **User**

## User [/user/{uid}/{token}]
Get detail of a user

+ Parameters
    + token (required, string, `abcdefghj`) ... Facebook Token
    + uid (required, string, `hnq90`) ... Facebook User Id

### Retrieve detail of a User [GET]
+ Response 200 (application/json)

    + Header

            X-Application: ZGVtb2RlbW9kZW1v

    + Body
    
            {
                "code": 0,
                "data": {
                    "id": 9, 
                    "name": "HuyNQ",
                    "type": 1,
                    "token": "abcdefghj",
                    "uid": "hnq90"
                }
            }
